# Generated by Django 4.1.7 on 2023-03-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_toy'),
    ]

    operations = [
        migrations.AddField(
            model_name='corgi',
            name='toys',
            field=models.ManyToManyField(to='main_app.toy'),
        ),
    ]
